@BASEURL = http://localhost:3000

### 新增優惠卷
POST {{BASEURL}}/api/admin/coupons
Content-Type: application/json

{
  "title": "老闆想不開",
  "is_enabled": true,
  "percent": 70,
  "effective_date": 1597994341942,
  "due_date": 1598198400000,
  "code": "a4"
}

### 取得優惠卷列表
GET {{BASEURL}}/api/admin/coupons

### 修改優惠卷
PATCH {{BASEURL}}/api/admin/coupons/-MFRQMovw4RekoW3HerL
Content-Type: application/json

{
  "percent": 45
}

### 修改優惠卷啟用狀態
PATCH {{BASEURL}}/api/admin/coupons/-MFU_XdCianbttgdnK0G/is_enabled
Content-Type: application/json

{
  "status": false
}

### 刪除優惠卷
DELETE {{BASEURL}}/api/admin/coupons/-MFRQMovw4RekoW3HerL, -MFRTS3kw2rLJSGx3kmM

